add mq configurations
cloudposse/terraform-aws-mq-broker pull request #67
Opened 2023-09-20 14:06 UTC by danushkaf

## what

This change is to allow users to configure MQ configurations with this module

## why

With current version there is no way to attach configurations to brokers

## references

[[[](https://github.com/cloudposse/terraform-aws-mq-broker/issues/66)]

2024-03-02 18:17 UTC, hans-d commented
/terratest

2024-03-04 08:52 UTC, hans-d commented
/terratest

2024-03-04 10:44 UTC, hans-d commented
/terratest

2024-03-05 00:42 UTC, hans-d commented
@danushkaf can you update this pr?
```
README.md is outdated. Please run the following commands locally and push the file:
  make init
  make readme
```
That way we can continue to process it, otherwise it's likely to be closed.

2024-05-07 18:27 UTC, matthewmrichter commented
Hi @hans-d, could we potentially revisit this PR? I don't know much about the failing tests, but it seems rather straightforward to me.

2025-03-20 18:50 UTC, GabisCampana commented
@goruha @osterman

2025-03-20 18:53 UTC, goruha requested changes

2025-03-20 18:53 UTC, goruha commented on main.tf
> +    for_each = local.configuration_data_create
are you sure you can iterate on bool?
```suggestion
            for_each = local.configuration_data_create
```

2025-03-20 18:53 UTC, goruha commented
@danushkaf could you check comments?

2025-03-20 18:53 UTC, goruha commented
/terratest

2025-03-20 19:32 UTC, goruha approved these changes

2025-03-20 19:32 UTC, merged